### ISSUE TITLE
Can the option to fork & re-direct output to /dev/null be added to this gem?

### ISSUE THREAD

**Issue by hackeron** [sophsec/ruby-nmap#38]
Currently, when I use ruby-nmap, my STDOUT is polluted with the output from nmap. Can a built-in way to suppress this output be added to this gem?

**Comment by postmodern** [comment]
I don't think nmap has a quiet option. You'd have to fork and redirect stdout.

**Comment by hackeron** [comment]
Ah, ok, updated the title to a feature request :)

**Comment by postmodern** [comment]
Now that nmap is on github, you should request a `--quiet` or `--silent` option. https://github.com/nmap/nmap/issues

ruby-nmap uses [rprogram](https://github.com/postmodern/rprogram#readme) to build and execute the commands. Maybe it could be added there, but I also kind of want to rewrite rprogram to support multiple types of execution (system, backticks, popen).

**Comment by xanview** [comment]
Nmap now supports -v0 to silence the output. Can ruby-nmap add an option to support it? :)

**Comment by postmodern** [comment]
@xanview I'm not seeing it in 7.01, was it just merged recently?

**Comment by xanview** [comment]
@postmodern 8 days ago with this commit: https://github.com/nmap/nmap/commit/b9367a6f53604ff01a7fa23f166a90905b78be58
