### ISSUE TITLE
Dealing with NSE

### ISSUE THREAD

**Issue by KINGSABRI** [sophsec/ruby-nmap#48]
Hi
Is there a way to parse and deal with NSE scripts? I mean, if we can deal with scripts as objects and set its arguments, particularly `--script-args=`

**Comment by kcning** [comment]
You can use #script_params, example:
```
# list databases on MySQL servers. Must have login credential
Nmap::Program.scan do |task|
  task.ports = 3306
  task.script = 'mysql-databases'
  task.script_params = 'mysqluser=<username>,'\
                       'mysqlpass=<password>' 
  task.targets = '<server>'
end
```

**Comment by postmodern** [comment]
For parsing the NSE output, see the [Scripts](http://www.rubydoc.info/gems/ruby-nmap/Nmap/Scripts) module, which provides `.scripts` raw output and `.script_data` parsed structured output, respectively. These methods are available on `xml.prescript`, `xml.postscript`, `host.host_script`, and any `port` object.

**Comment by KINGSABRI** [comment]
@kcning @postmodern Thank you guys, both answers combined are all that I needed
