### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by noraj** [sophsec/ruby-nmap#54]
Have you a comparison between ruby-nmap and Ruby Nmap::Parser ([project](https://sourceforge.net/projects/rubynmap/) - [doc](http://rubynmap.sourceforge.net/doc/index.html))?

I'm curious to know the technical power of each one.

**Comment by postmodern** [comment]
1. It appears to be very old and doesn't appear to be actively maintained.
2. The [README](https://sourceforge.net/p/rubynmap/code/HEAD/tree/trunk/) mentions REXML (the old/deprecated pure-Ruby XML parser) and Ruby 1.9.1. Where as ruby-nmap uses [Nokogiri](https://rubygems.org/gems/nokogiri) which uses the `libxml2` C library. REXML is much slower than Nokogiri and is not recommended anymore.
3. It probably doesn't support newer XML elements that nmap has added to their [XML DTD](https://github.com/nmap/nmap/blob/master/docs/nmap.dtd) over the years.
4. It doesn't support mapping Ruby options/attributes to nmap's command line options. Instead you just pass in [the raw command line arguments](https://sourceforge.net/p/rubynmap/code/HEAD/tree/trunk/lib/nmap/parser.rb#l365).
