### ISSUE TITLE
RProgram::ProgramNotFound: programs "nmap" were not found

### ISSUE THREAD

**Issue by hahwul** [sophsec/ruby-nmap#56]
I running ruby-nmap on heroku, but i see this error 
```
RProgram::ProgramNotFound: programs "nmap" were not found
```

Can I possibly direct the binary path route?
please reply me!

Cheers!

**Comment by postmodern** [comment]
Is nmap even installed? I don't believe Heroku will let you install nmap.

[Nmap::Program](https://rubydoc.info/gems/ruby-nmap/Nmap/Program) inherits from [RProgram::Program](https://rubydoc.info/gems/rprogram/RProgram/Program), which provides various methods for finding installed programs or specifying the fully qualified path to the binary. So you would need to create the `Nmap::Program` object, then call `scan`/`sudo_scan`.

**Comment by postmodern** [comment]
```ruby
Nmap::Program.new("/path/to/nmap").scan do |nmap|
  nmap.ports = ...
  ...
end

Nmap::Program.new("/path/to/nmap").sudo_scan do |nmap|
  nmap.ports = ...
  ...
end
```
